site_name: OpenDbt
site_url: http://memiiso.github.io/opendbt
repo_url: https://github.com/memiiso/opendbt
theme:
  name: material
  features:
    #    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    #    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.tabs.link
nav:
  - Home: index.md
  - Using Custom Adapter: adapter_integration.md
  - Python(Local) Model: python_integration.md
  - DLT Model: dlt_integration.md
  - Examples: examples.md
  - Data Catalog: catalog.md
  - Data Catalog (Demo): opendbtdocs/index.html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      check_paths: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg